function ret = mpfr_root (rop, op, n, rnd)
% ret = mpfr_root (rop, op, n, rnd)
%
% This function is the same as ‘mpfr_rootn_ui’ except when OP is −0
% and N is even: the result is −0 instead of +0 (the reason was to be
% consistent with ‘mpfr_sqrt’).  Said otherwise, if OP is zero, set
% ROP to OP.
%
% This function predates the IEEE 754-2008 standard and behaves
% differently from its rootn function.  It is marked as deprecated
% and will be removed in a future release.
%

  if (isa (rop, 'mpfr_t'))
    rop = rop.idx;
  end
  if (isa (op, 'mpfr_t'))
    op = op.idx;
  end
  ret = gmp_mpfr_interface (47, rop, op, n, rnd);
end

% This function was automatically generated by "generate_m_files".
