function [significant, expptr] = mpfr_get_str (base, n, op, rnd)
  if (isa (op, 'mpfr_t'))
    op = op.idx;
  end
  [significant, expptr] = gmp_mpfr_interface (21, base, n, op, rnd);
end

% This function was automatically generated by "generate_m_files".
