function ret = mpfr_buildopt_decimal_p ()
% ret = mpfr_buildopt_decimal_p ()
%
% Return a non-zero value if MPFR was compiled with decimal float
% support (that is, MPFR was built with the ‘--enable-decimal-float’
% configure option), return zero otherwise.
%

  ret = mex_apa_interface (1184);
end

% This function was automatically generated by "generate_m_files".
