function ret = mpfr_dim (rop, op1, op2, rnd)
% ret = mpfr_dim (rop, op1, op2, rnd)
%
% Set ROP to the positive difference of OP1 and OP2, i.e., OP1 - OP2
% rounded in the direction RND if OP1 > OP2, +0 if OP1 <= OP2, and
% NaN if OP1 or OP2 is NaN.
%

  ret = mex_apa_interface (1050, rop, op1, op2, rnd);
end

% This function was automatically generated by "generate_m_files".
