function ret = mpfr_exp10 (rop, op, rnd)
% Set ROP to the exponential of OP, to 2 power of OP or to 10 power
% of OP, respectively, rounded in the direction RND.
%

  if (isa (rop, 'mpfr_t'))
    rop = rop.idx;
  end
  if (isa (op, 'mpfr_t'))
    op = op.idx;
  end
  ret = gmp_mpfr_interface (90, rop, op, rnd);
end

% This function was automatically generated by "generate_m_files".
