function ret = mpfr_integer_p (op)
% ret = mpfr_integer_p (op)
%
% Return non-zero iff OP is an integer.
%

  if (isa (op, 'mpfr_t'))
    op = op.idx;
  end
  ret = gmp_mpfr_interface (160, op);
end

% This function was automatically generated by "generate_m_files".
