function ret = mpfr_get_version ()
% ret = mpfr_get_version ()
%
% Return the MPFR version, as a null-terminated string.
%

  ret = mex_apa_interface (1181);
end

% This function was automatically generated by "generate_m_files".
