function ret = MPFR_RNDZ ()
% ret = MPFR_RNDZ ()
%
% Return internal numerical value for the rounding mode
% "round toward minus infinity" (roundTowardNegative in IEEE 754-2008).

  ret = mex_apa_interface (1401);
end

% This function was automatically generated by "generate_m_files".
