function ret = mpfr_init_set_str (x, *s, base, rnd)
  if (isa (x, 'mpfr_t'))
    x = x.idx;
  else
    error ('x must be a "mpfr_t" variable');
  end
  ret = gmp_mpfr_interface (16, x, *s, base, rnd);
end

% This function was automatically generated by "generate_m_files".
