function ret = MPFR_RNDA ()
% ret = MPFR_RNDA ()
%
% Return internal numerical value for the rounding mode
% "round away from zero".

  ret = mex_apa_interface (1304);
end

% This function was automatically generated by "generate_m_files".
