function ret = mpfr_subnormalize (x, t, rnd)
  if (isa (x, 'mpfr_t'))
    x = x.idx;
  end
  ret = gmp_mpfr_interface (197, x, t, rnd);
end

% This function was automatically generated by "generate_m_files".
