function ret = mpfr_sqr (rop, op, rnd)
% ret = mpfr_sqr (rop, op, rnd)
%
% Set ROP to the square of OP rounded in the direction RND.
%

  if (isa (rop, 'mpfr_t'))
    rop = rop.idx;
  end
  if (isa (op, 'mpfr_t'))
    op = op.idx;
  end
  ret = mex_apa_interface (1038, rop, op, rnd);
end

% This function was automatically generated by "generate_m_files".
