function ret = mpfr_cbrt (rop, op, rnd)
% ret = mpfr_cbrt (rop, op, rnd)
%
% Set ROP to the Nth root (with N = 3, the cubic root, for
% ‘mpfr_cbrt’) of OP rounded in the direction RND.  For N = 0, set
% ROP to NaN.  For N odd (resp. even) and OP negative (including
% −Inf), set ROP to a negative number (resp. NaN).  If OP is zero,
% set ROP to zero with the sign obtained by the usual limit rules,
% i.e., the same sign as OP if N is odd, and positive if N is even.
%
% These functions agree with the rootn operation of the IEEE 754
% standard.
%

  ret = mex_apa_interface (1045, rop, op, rnd);
end

% This function was automatically generated by "generate_m_files".
