function mpfr_nexttoward (x, y)
% mpfr_nexttoward (x, y)
%
% If X or Y is NaN, set X to NaN; note that the NaN flag is set as
% usual.  If X and Y are equal, X is unchanged.  Otherwise, if X is
% different from Y, replace X by the next floating-point number (with
% the precision of X and the current exponent range) in the direction
% of Y (the infinite values are seen as the smallest and largest
% floating-point numbers).  If the result is zero, it keeps the same
% sign.  No underflow, overflow, or inexact exception is raised.
%

  mex_apa_interface (1166, x, y);
end

% This function was automatically generated by "generate_m_files".
