function ret = mpfr_set_ui_2exp (rop, op, e, rnd)
  if (isa (rop, 'mpfr_t'))
    rop = rop.idx;
  end
  ret = gmp_mpfr_interface (7, rop, op, e, rnd);
end

% This function was automatically generated by "generate_m_files".
