function ret = mpfr_zero_p (op)
% ret = mpfr_zero_p (op)
%
% Return non-zero if OP is respectively NaN, an infinity, an ordinary
% number (i.e., neither NaN nor an infinity), zero, or a regular
% number (i.e., neither NaN, nor an infinity nor zero).  Return zero
% otherwise.
%

  if (isa (op, 'mpfr_t'))
    op = op.idx;
  end
  ret = gmp_mpfr_interface (72, op);
end

% This function was automatically generated by "generate_m_files".
