function ret = mpfr_copysign (rop, op1, op2, rnd)
% ret = mpfr_copysign (rop, op1, op2, rnd)
%
% Set the value of ROP from OP1, rounded toward the given direction
% RND, then set its sign bit to that of OP2 (even when OP1 or OP2 is
% a NaN).  This function is equivalent to ‘mpfr_setsign (ROP, OP1,
% mpfr_signbit (OP2), RND)’.
%

  if (isa (rop, 'mpfr_t'))
    rop = rop.idx;
  end
  if (isa (op1, 'mpfr_t'))
    op1 = op1.idx;
  end
  if (isa (op2, 'mpfr_t'))
    op2 = op2.idx;
  end
  ret = gmp_mpfr_interface (180, rop, op1, op2, rnd);
end

% This function was automatically generated by "generate_m_files".
