function ret = mpfr_lessgreater_p (op1, op2)
% ret = mpfr_lessgreater_p (op1, op2)
%
% Return non-zero if OP1 < OP2 or OP1 > OP2 (i.e., neither OP1, nor
% OP2 is NaN, and OP1 <> OP2), zero otherwise (i.e., OP1 and/or OP2
% is NaN, or OP1 = OP2).
%

  ret = mex_apa_interface (1080, op1, op2);
end

% This function was automatically generated by "generate_m_files".
