function ret = mpfr_dot (rop, a[], b[], n, rnd)
  if (isa (rop, 'mpfr_t'))
    rop = rop.idx;
  else
    error ('rop must be a "mpfr_t" variable');
  end
  ret = gmp_mpfr_interface (62, rop, a[], b[], n, rnd);
end

% This function was automatically generated by "generate_m_files".
