function mpfr_nextabove (x)
  if (isa (x, 'mpfr_t'))
    x = x.idx;
  else
    error ('x must be a "mpfr_t" variable');
  end
  gmp_mpfr_interface (167, x);
end

% This function was automatically generated by "generate_m_files".
