function ret = mpfr_get_version ()
% ret = mpfr_get_version ()
%
% Return the MPFR version, as a null-terminated string.
%

  ret = gmp_mpfr_interface (181);
end

% This function was automatically generated by "generate_m_files".
