function mpfr_inits (varargin)
% mpfr_inits (varargin)
%
% This function does nothing (NOP)!
%
% Initialize all the ‘mpfr_t’ variables of the given ‘va_list’, set
% their precision to the default precision and their value to NaN.
% See ‘mpfr_init’ for more details.  The ‘va_list’ is assumed to be
% composed only of type ‘mpfr_t’ (or equivalently ‘mpfr_ptr’).  It
% begins from X, and ends when it encounters a null pointer (whose
% type must also be ‘mpfr_ptr’).
%
% Warning!  In a given program, some other libraries might change the
% default precision and not restore it.  Thus it is safer to use
% ‘mpfr_inits2’.
%

  mex_apa_interface (1800, varargin{:});
end

% This function was automatically generated by "generate_m_files".
