function mpfr_set_nan (x)
% mpfr_set_nan (x)
%
% Set the variable X to NaN (Not-a-Number), infinity or zero
% respectively.  In ‘mpfr_set_inf’ or ‘mpfr_set_zero’, X is set to
% plus infinity or plus zero iff SIGN is nonnegative; in
% ‘mpfr_set_nan’, the sign bit of the result is unspecified.
%

  if (isa (x, 'mpfr_t'))
    x = x.idx;
  end
  gmp_mpfr_interface (10, x);
end

% This function was automatically generated by "generate_m_files".
