function ret = mpfr_less_p (op1, op2)
% ret = mpfr_less_p (op1, op2)
%
% Return non-zero if OP1 > OP2, OP1 >= OP2, OP1 < OP2, OP1 <= OP2,
% OP1 = OP2 respectively, and zero otherwise.  Those functions return
% zero whenever OP1 and/or OP2 is NaN.
%

  ret = mex_apa_interface (1077, op1, op2);
end

% This function was automatically generated by "generate_m_files".
