function ret = mpfr_fac_ui (rop, op, rnd)
  if (isa (rop, 'mpfr_t'))
    rop = rop.idx;
  end
  ret = gmp_mpfr_interface (55, rop, op, rnd);
end

% This function was automatically generated by "generate_m_files".
