function ret = mpfr_erfc (rop, op, rnd)
% ret = mpfr_erfc (rop, op, rnd)
%
% Set ROP to the value of the error function on OP (resp. the
% complementary error function on OP) rounded in the direction RND.
%

  ret = mex_apa_interface (1130, rop, op, rnd);
end

% This function was automatically generated by "generate_m_files".
