function ret = MPFR_RNDN ()
% ret = MPFR_RNDN ()
%
% Return internal numerical value for the rounding mode
% "round to nearest", with the even rounding rule (roundTiesToEven in IEEE 754-2008).

  ret = mex_apa_interface (1400);
end

% This function was automatically generated by "generate_m_files".
