function mpfr_set_divby0 ()
% mpfr_set_divby0 ()
%
% Set (raise) the underflow, overflow, divide-by-zero, invalid,
% inexact and _erange_ flags.
%

  mex_apa_interface (1207);
end

% This function was automatically generated by "generate_m_files".
