function ret = mpfr_set_exp (x, e)
  if (isa (x, 'mpfr_t'))
    x = x.idx;
  else
    error ('x must be a "mpfr_t" variable');
  end
  ret = gmp_mpfr_interface (177, x, e);
end

% This function was automatically generated by "generate_m_files".
