function [ret, q] = mpfr_fmodquo (r, x, y, rnd)
  if (isa (r, 'mpfr_t'))
    r = r.idx;
  end
  if (isa (x, 'mpfr_t'))
    x = x.idx;
  end
  if (isa (y, 'mpfr_t'))
    y = y.idx;
  end
  [ret, q] = gmp_mpfr_interface (157, r, x, y, rnd);
end

% This function was automatically generated by "generate_m_files".
