function mpfr_set_inexflag ()
% mpfr_set_inexflag ()
%
% Set (raise) the underflow, overflow, divide-by-zero, invalid,
% inexact and _erange_ flags.
%

  mex_apa_interface (1209);
end

% This function was automatically generated by "generate_m_files".
