function ret = mpfr_div_d (rop, op1, op2, rnd)
  if (isa (rop, 'mpfr_t'))
    rop = rop.idx;
  end
  if (isa (op1, 'mpfr_t'))
    op1 = op1.idx;
  end
  ret = gmp_mpfr_interface (41, rop, op1, op2, rnd);
end

% This function was automatically generated by "generate_m_files".
