function mpfr_clear_overflow ()
% mpfr_clear_overflow ()
%
% Clear (lower) the underflow, overflow, divide-by-zero, invalid,
% inexact and _erange_ flags.
%

  mex_apa_interface (1199);
end

% This function was automatically generated by "generate_m_files".
