function ret = mpfr_modf (iop, fop, op, rnd)
  if (isa (iop, 'mpfr_t'))
    iop = iop.idx;
  else
    error ('iop must be a "mpfr_t" variable');
  end
  if (isa (fop, 'mpfr_t'))
    fop = fop.idx;
  else
    error ('fop must be a "mpfr_t" variable');
  end
  if (isa (op, 'mpfr_t'))
    op = op.idx;
  else
    error ('op must be a "mpfr_t" variable');
  end
  ret = gmp_mpfr_interface (155, iop, fop, op, rnd);
end

% This function was automatically generated by "generate_m_files".
