function mpfr_clear_erangeflag ()
% mpfr_clear_erangeflag ()
%
% Clear (lower) the underflow, overflow, divide-by-zero, invalid,
% inexact and _erange_ flags.
%

  gmp_mpfr_interface (203);
end

% This function was automatically generated by "generate_m_files".
