function ret = mpfr_atan2 (rop, y, x, rnd)
  if (isa (rop, 'mpfr_t'))
    rop = rop.idx;
  end
  if (isa (y, 'mpfr_t'))
    y = y.idx;
  end
  if (isa (x, 'mpfr_t'))
    x = x.idx;
  end
  ret = gmp_mpfr_interface (108, rop, y, x, rnd);
end

% This function was automatically generated by "generate_m_files".
