function ret = mpfr_expm1 (rop, op, rnd)
% ret = mpfr_expm1 (rop, op, rnd)
%
% Set ROP to the exponential of OP followed by a subtraction by one,
% rounded in the direction RND.
%

  ret = mex_apa_interface (1091, rop, op, rnd);
end

% This function was automatically generated by "generate_m_files".
