function ret = mpfr_unordered_p (op1, op2)
% ret = mpfr_unordered_p (op1, op2)
%
% Return non-zero if OP1 or OP2 is a NaN (i.e., they cannot be
% compared), zero otherwise.
%

  if (isa (op1, 'mpfr_t'))
    op1 = op1.idx;
  end
  if (isa (op2, 'mpfr_t'))
    op2 = op2.idx;
  end
  ret = gmp_mpfr_interface (81, op1, op2);
end

% This function was automatically generated by "generate_m_files".
