function ret = mpfr_divby0_p ()
% ret = mpfr_divby0_p ()
%
% Return the corresponding (underflow, overflow, divide-by-zero,
% invalid, inexact, _erange_) flag, which is non-zero iff the flag is
% set.
%

  ret = gmp_mpfr_interface (213);
end

% This function was automatically generated by "generate_m_files".
