function mpfr_set_nan (x)
  if (isa (x, 'mpfr_t'))
    x = x.idx;
  else
    error ('x must be a "mpfr_t" variable');
  end
  gmp_mpfr_interface (10, x);
end

% This function was automatically generated by "generate_m_files".
