function ret = mpfr_set_si_2exp (rop, op, e, rnd)
% ret = mpfr_set_si_2exp (rop, op, e, rnd)
%
% Set the value of ROP from OP multiplied by two to the power E,
% rounded toward the given direction RND.  Note that the input 0 is
% converted to +0.
%

  ret = mex_apa_interface (1008, rop, op, e, rnd);
end

% This function was automatically generated by "generate_m_files".
