function ret = mpfr_zeta_ui (rop, op, rnd)
% ret = mpfr_zeta_ui (rop, op, rnd)
%
% Set ROP to the value of the Riemann Zeta function on OP, rounded in
% the direction RND.
%

  ret = mex_apa_interface (1128, rop, op, rnd);
end

% This function was automatically generated by "generate_m_files".
