function ret = mpfr_integer_p (op)
% ret = mpfr_integer_p (op)
%
% Return non-zero iff OP is an integer.
%

  ret = mex_apa_interface (1160, op);
end

% This function was automatically generated by "generate_m_files".
