function [ret, signp] = mpfr_lgamma (rop, op, rnd)
  if (isa (rop, 'mpfr_t'))
    rop = rop.idx;
  end
  if (isa (op, 'mpfr_t'))
    op = op.idx;
  end
  [ret, signp] = gmp_mpfr_interface (124, rop, op, rnd);
end

% This function was automatically generated by "generate_m_files".
