function ret = mpfr_tanh (rop, op, rnd)
% ret = mpfr_tanh (rop, op, rnd)
%
% Set ROP to the hyperbolic cosine, sine or tangent of OP, rounded in
% the direction RND.
%

  ret = mex_apa_interface (1111, rop, op, rnd);
end

% This function was automatically generated by "generate_m_files".
