function ret = mpfr_set_si_2exp (rop, op, e, rnd)
  if (isa (rop, 'mpfr_t'))
    rop = rop.idx;
  else
    error ('rop must be a "mpfr_t" variable');
  end
  ret = gmp_mpfr_interface (8, rop, op, e, rnd);
end

% This function was automatically generated by "generate_m_files".
