function ret = mpfr_buildopt_tls_p ()
% ret = mpfr_buildopt_tls_p ()
%
% Return a non-zero value if MPFR was compiled as thread safe using
% compiler-level Thread-Local Storage (that is, MPFR was built with
% the ‘--enable-thread-safe’ configure option, see ‘INSTALL’ file),
% return zero otherwise.
%

  ret = mex_apa_interface (1182);
end

% This function was automatically generated by "generate_m_files".
