function ret = mpfr_get_exp (x)
% Return the exponent of X, assuming that X is a non-zero ordinary
% number and the significand is considered in [1/2,1).  For this
% function, X is allowed to be outside of the current range of
% acceptable values.  The behavior for NaN, infinity or zero is
% undefined.
%

  if (isa (x, 'mpfr_t'))
    x = x.idx;
  end
  ret = gmp_mpfr_interface (176, x);
end

% This function was automatically generated by "generate_m_files".
