function ret = mpfr_buildopt_float128_p ()
% ret = mpfr_buildopt_float128_p ()
%
% Return a non-zero value if MPFR was compiled with binary128 support
% (a.k.a. float128), return zero otherwise.  *Note Nomenclature and
% Types:: for additional information.
%

  ret = mex_apa_interface (1183);
end

% This function was automatically generated by "generate_m_files".
