function mpfr_set_nanflag ()
% mpfr_set_nanflag ()
%
% Set (raise) the underflow, overflow, divide-by-zero, invalid,
% inexact and _erange_ flags.
%

  mex_apa_interface (1208);
end

% This function was automatically generated by "generate_m_files".
