function mpfr_clear_nanflag ()
% mpfr_clear_nanflag ()
%
% Clear (lower) the underflow, overflow, divide-by-zero, invalid,
% inexact and _erange_ flags.
%

  gmp_mpfr_interface (201);
end

% This function was automatically generated by "generate_m_files".
