function mpfr_set_default_rounding_mode (rnd)
% mpfr_set_default_rounding_mode (rnd)
%
% Set the default rounding mode to RND.  The default rounding mode is
% to nearest initially.
%

  mex_apa_interface (1161, rnd);
end

% This function was automatically generated by "generate_m_files".
