function ret = mpfr_set_str (rop, *s, base, rnd)
  if (isa (rop, 'mpfr_t'))
    rop = rop.idx;
  end
  ret = gmp_mpfr_interface (9, rop, *s, base, rnd);
end

% This function was automatically generated by "generate_m_files".
