function mpfr_clear_divby0 ()
% Clear (lower) the underflow, overflow, divide-by-zero, invalid,
% inexact and _erange_ flags.
%

  gmp_mpfr_interface (200);
end

% This function was automatically generated by "generate_m_files".
