function ret = mpfr_set_ui_2exp (rop, op, e, rnd)
% Set the value of ROP from OP multiplied by two to the power E,
% rounded toward the given direction RND.  Note that the input 0 is
% converted to +0.
%

  if (isa (rop, 'mpfr_t'))
    rop = rop.idx;
  end
  ret = gmp_mpfr_interface (7, rop, op, e, rnd);
end

% This function was automatically generated by "generate_m_files".
