function ret = mpfr_signbit (op)
% Return a non-zero value iff OP has its sign bit set (i.e., if it is
% negative, −0, or a NaN whose representation has its sign bit set).
%

  if (isa (op, 'mpfr_t'))
    op = op.idx;
  end
  ret = gmp_mpfr_interface (178, op);
end

% This function was automatically generated by "generate_m_files".
