function ret = mpfr_ai (rop, x, rnd)
  if (isa (rop, 'mpfr_t'))
    rop = rop.idx;
  end
  if (isa (x, 'mpfr_t'))
    x = x.idx;
  end
  ret = gmp_mpfr_interface (138, rop, x, rnd);
end

% This function was automatically generated by "generate_m_files".
