function mpfr_clear (varargin)
% mpfr_clear (varargin)
%
% This function does nothing (NOP)!
%
% Free the space occupied by the significand of X.  Make sure to call
% this function for all ‘mpfr_t’ variables when you are done with
% them.
%

  mex_apa_interface (1802, varargin{:});
end

% This function was automatically generated by "generate_m_files".
