function ret = mpfr_set_exp (x, e)
% ret = mpfr_set_exp (x, e)
%
% Set the exponent of X to E if X is a non-zero ordinary number and E
% is in the current exponent range, and return 0; otherwise, return a
% non-zero value (X is not changed).
%

  ret = mex_apa_interface (1177, x, e);
end

% This function was automatically generated by "generate_m_files".
