function ret = mpfr_fmms (rop, op1, op2, op3, op4, rnd)
% ret = mpfr_fmms (rop, op1, op2, op3, op4, rnd)
%
% Set ROP to (OP1 times OP2) + (OP3 times OP4) (resp. (OP1 times OP2)
% - (OP3 times OP4)) rounded in the direction RND.  In case the
% computation of OP1 times OP2 overflows or underflows (or that of
% OP3 times OP4), the result ROP is computed as if the two
% intermediate products were computed with rounding toward zero.
%

  ret = mex_apa_interface (1059, rop, op1, op2, op3, op4, rnd);
end

% This function was automatically generated by "generate_m_files".
