function mpfr_inits2 (varargin)
% mpfr_inits2 (varargin)
%
% This function does nothing (NOP)!
%
% Initialize all the ‘mpfr_t’ variables of the given variable
% argument ‘va_list’, set their precision to be *exactly* PREC bits
% and their value to NaN.  See ‘mpfr_init2’ for more details.  The
% ‘va_list’ is assumed to be composed only of type ‘mpfr_t’ (or
% equivalently ‘mpfr_ptr’).  It begins from X, and ends when it
% encounters a null pointer (whose type must also be ‘mpfr_ptr’).
%

  mex_apa_interface (1801, varargin{:});
end

% This function was automatically generated by "generate_m_files".
