function ret = mpfr_frac (rop, op, rnd)
% ret = mpfr_frac (rop, op, rnd)
%
% Set ROP to the fractional part of OP, having the same sign as OP,
% rounded in the direction RND (unlike in ‘mpfr_rint’, RND affects
% only how the exact fractional part is rounded, not how the
% fractional part is generated).  When OP is an integer or an
% infinity, set ROP to zero with the same sign as OP.
%

  ret = mex_apa_interface (1154, rop, op, rnd);
end

% This function was automatically generated by "generate_m_files".
