function ret = mpfr_li2 (rop, op, rnd)
% Set ROP to real part of the dilogarithm of OP, rounded in the
% direction RND.  MPFR defines the dilogarithm function as the
% integral of -log(1-t)/t from 0 to OP.
%

  if (isa (rop, 'mpfr_t'))
    rop = rop.idx;
  end
  if (isa (op, 'mpfr_t'))
    op = op.idx;
  end
  ret = gmp_mpfr_interface (120, rop, op, rnd);
end

% This function was automatically generated by "generate_m_files".
