function ret = mpfr_get_default_prec ()
% ret = mpfr_get_default_prec ()
%
% Return the current default MPFR precision in bits.  See the
% documentation of ‘mpfr_set_default_prec’.
%

  ret = mex_apa_interface (1002);
end

% This function was automatically generated by "generate_m_files".
