function ret = mpfr_init_set_str (x, s, base, rnd)
% ret = mpfr_init_set_str (x, s, base, rnd)
%
% Initialize X and set its value from the string S in base BASE,
% rounded in the direction RND.  See ‘mpfr_set_str’.
%

  ret = mex_apa_interface (1016, x, s, base, rnd);
end

% This function was automatically generated by "generate_m_files".
