function ret = mpfr_sqrt (rop, op, rnd)
% ret = mpfr_sqrt (rop, op, rnd)
%
% Set ROP to the square root of OP rounded in the direction RND.  Set
% ROP to −0 if OP is −0, to be consistent with the IEEE 754 standard.
% Set ROP to NaN if OP is negative.
%

  if (isa (rop, 'mpfr_t'))
    rop = rop.idx;
  end
  if (isa (op, 'mpfr_t'))
    op = op.idx;
  end
  ret = gmp_mpfr_interface (42, rop, op, rnd);
end

% This function was automatically generated by "generate_m_files".
