function ret = mpfr_cmpabs_ui (op1, op2)
% ret = mpfr_cmpabs_ui (op1, op2)
%
% Compare |OP1| and |OP2|.  Return a positive value if |OP1| > |OP2|,
% zero if |OP1| = |OP2|, and a negative value if |OP1| < |OP2|.  If
% one of the operands is NaN, set the _erange_ flag and return zero.
%

  ret = mex_apa_interface (1068, op1, op2);
end

% This function was automatically generated by "generate_m_files".
