function ret = mpfr_expm1 (rop, op, rnd)
% Set ROP to the exponential of OP followed by a subtraction by one,
% rounded in the direction RND.
%

  if (isa (rop, 'mpfr_t'))
    rop = rop.idx;
  end
  if (isa (op, 'mpfr_t'))
    op = op.idx;
  end
  ret = gmp_mpfr_interface (91, rop, op, rnd);
end

% This function was automatically generated by "generate_m_files".
