function ret = mpfr_acosh (rop, op, rnd)
% ret = mpfr_acosh (rop, op, rnd)
%
% Set ROP to the inverse hyperbolic cosine, sine or tangent of OP,
% rounded in the direction RND.
%

  ret = mex_apa_interface (1116, rop, op, rnd);
end

% This function was automatically generated by "generate_m_files".
