function mpfr_set_erangeflag ()
% Set (raise) the underflow, overflow, divide-by-zero, invalid,
% inexact and _erange_ flags.
%

  gmp_mpfr_interface (210);
end

% This function was automatically generated by "generate_m_files".
