function ret = mpfr_min_prec (x)
  if (isa (x, 'mpfr_t'))
    x = x.idx;
  else
    error ('x must be a "mpfr_t" variable');
  end
  ret = gmp_mpfr_interface (165, x);
end

% This function was automatically generated by "generate_m_files".
