function mpfr_set_overflow ()
% mpfr_set_overflow ()
%
% Set (raise) the underflow, overflow, divide-by-zero, invalid,
% inexact and _erange_ flags.
%

  mex_apa_interface (1206);
end

% This function was automatically generated by "generate_m_files".
