function ret = mpfr_hypot (rop, x, y, rnd)
  if (isa (rop, 'mpfr_t'))
    rop = rop.idx;
  else
    error ('rop must be a "mpfr_t" variable');
  end
  if (isa (x, 'mpfr_t'))
    x = x.idx;
  else
    error ('x must be a "mpfr_t" variable');
  end
  if (isa (y, 'mpfr_t'))
    y = y.idx;
  else
    error ('y must be a "mpfr_t" variable');
  end
  ret = gmp_mpfr_interface (60, rop, x, y, rnd);
end

% This function was automatically generated by "generate_m_files".
