function mpfr_nextbelow (x)
% mpfr_nextbelow (x)
%
% Equivalent to ‘mpfr_nexttoward’ where Y is +Inf (resp. −Inf).
%

  mex_apa_interface (1168, x);
end

% This function was automatically generated by "generate_m_files".
