function ret = mpfr_erf (rop, op, rnd)
% Set ROP to the value of the error function on OP (resp. the
% complementary error function on OP) rounded in the direction RND.
%

  if (isa (rop, 'mpfr_t'))
    rop = rop.idx;
  end
  if (isa (op, 'mpfr_t'))
    op = op.idx;
  end
  ret = gmp_mpfr_interface (129, rop, op, rnd);
end

% This function was automatically generated by "generate_m_files".
