function mpfr_clears (varargin)
% mpfr_clears (varargin)
%
% This function does nothing (NOP)!
%
% Free the space occupied by all the ‘mpfr_t’ variables of the given
% ‘va_list’.  See ‘mpfr_clear’ for more details.  The ‘va_list’ is
% assumed to be composed only of type ‘mpfr_t’ (or equivalently
% ‘mpfr_ptr’).  It begins from X, and ends when it encounters a null
% pointer (whose type must also be ‘mpfr_ptr’).
%

  mex_apa_interface (1803, varargin{:});
end

% This function was automatically generated by "generate_m_files".
