function ret = mpfr_roundeven (rop, op)
  if (isa (rop, 'mpfr_t'))
    rop = rop.idx;
  end
  if (isa (op, 'mpfr_t'))
    op = op.idx;
  end
  ret = gmp_mpfr_interface (147, rop, op);
end

% This function was automatically generated by "generate_m_files".
