function ret = mpfr_fac_ui (rop, op, rnd)
% ret = mpfr_fac_ui (rop, op, rnd)
%
% Set ROP to the factorial of OP, rounded in the direction RND.
%

  ret = mex_apa_interface (1055, rop, op, rnd);
end

% This function was automatically generated by "generate_m_files".
