function ret = mpfr_rootn_ui (rop, op, n, rnd)
  if (isa (rop, 'mpfr_t'))
    rop = rop.idx;
  end
  if (isa (op, 'mpfr_t'))
    op = op.idx;
  end
  ret = gmp_mpfr_interface (46, rop, op, n, rnd);
end

% This function was automatically generated by "generate_m_files".
