function [ret, endptr] = mpfr_strtofr (rop, nptr, base, rnd)
  if (isa (rop, 'mpfr_t'))
    rop = rop.idx;
  end
  [ret, endptr] = gmp_mpfr_interface (217, rop, nptr, base, rnd);
end

% This function was automatically generated by "generate_m_files".
