function ret = mpfr_buildopt_tune_case ()
% ret = mpfr_buildopt_tune_case ()
%
% Return a string saying which thresholds file has been used at
% compile time.  This file is normally selected from the processor
% type.
%

  ret = mex_apa_interface (1187);
end

% This function was automatically generated by "generate_m_files".
