function ret = mpfr_remainder (r, x, y, rnd)
  if (isa (r, 'mpfr_t'))
    r = r.idx;
  end
  if (isa (x, 'mpfr_t'))
    x = x.idx;
  end
  if (isa (y, 'mpfr_t'))
    y = y.idx;
  end
  ret = gmp_mpfr_interface (158, r, x, y, rnd);
end

% This function was automatically generated by "generate_m_files".
