function ret = mpfr_exp (rop, op, rnd)
% ret = mpfr_exp (rop, op, rnd)
%
% Set ROP to the exponential of OP, to 2 power of OP or to 10 power
% of OP, respectively, rounded in the direction RND.
%

  ret = mex_apa_interface (1088, rop, op, rnd);
end

% This function was automatically generated by "generate_m_files".
