function ret = mpfr_buildopt_tune_case ()
% Return a string saying which thresholds file has been used at
% compile time.  This file is normally selected from the processor
% type.
%

  ret = gmp_mpfr_interface (187);
end

% This function was automatically generated by "generate_m_files".
