function ret = mpfr_mul_2ui (rop, op1, op2, rnd)
% ret = mpfr_mul_2ui (rop, op1, op2, rnd)
%
% Set ROP to OP1 times 2 raised to OP2 rounded in the direction RND.
% Just increases the exponent by OP2 when ROP and OP1 are identical.
%

  ret = mex_apa_interface (1051, rop, op1, op2, rnd);
end

% This function was automatically generated by "generate_m_files".
