function ret = mpfr_ui_pow_ui (rop, op1, op2, rnd)
  if (isa (rop, 'mpfr_t'))
    rop = rop.idx;
  end
  ret = gmp_mpfr_interface (96, rop, op1, op2, rnd);
end

% This function was automatically generated by "generate_m_files".
