function ret = mpfr_csch (rop, op, rnd)
% ret = mpfr_csch (rop, op, rnd)
%
% Set ROP to the hyperbolic secant of OP, cosecant of OP, cotangent
% of OP, rounded in the direction RND.
%

  ret = mex_apa_interface (1114, rop, op, rnd);
end

% This function was automatically generated by "generate_m_files".
